yewtube: add `ffmpeg` dependency
Fixes test failure:
```
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple
formats but ffmpeg is not installed. Aborting due to --abort-on-error
```