parquet-cli: switch to `openjdk@21`
Test failure with `openjdk` 23:

    ==> Testing parquet-cli
    ==> /usr/local/Cellar/parquet-cli/1.14.1_1/bin/parquet schema /usr/local/Cellar/parquet-cli/1.14.1_1/share/parquet-cli/test/stringBehavior.avsc
    Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
    Unknown error
    java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed
      at java.base/javax.security.auth.Subject.getSubject(Subject.java:347)
      at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:577)
      at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3884)
      at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3874)
      at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3662)
      at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:557)
      at org.apache.hadoop.fs.FileSystem.getLocal(FileSystem.java:510)
      at org.apache.parquet.cli.BaseCommand.defaultFS(BaseCommand.java:81)
      at org.apache.parquet.cli.BaseCommand.qualifiedPath(BaseCommand.java:179)
      at org.apache.parquet.cli.BaseCommand.openSeekable(BaseCommand.java:231)
      at org.apache.parquet.cli.BaseCommand.getAvroSchema(BaseCommand.java:390)
      at org.apache.parquet.cli.commands.SchemaCommand.getSchema(SchemaCommand.java:104)
      at org.apache.parquet.cli.commands.SchemaCommand.run(SchemaCommand.java:82)
      at org.apache.parquet.cli.Main.run(Main.java:163)
      at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:82)
      at org.apache.parquet.cli.Main.main(Main.java:191)