openldap: update `inreplace` syntax
Fixes:

    MethodDeprecatedError: Calling inreplace(paths, before, after, false) is deprecated! Use inreplace(paths, before, after, audit_result: false) instead.
    Please report this issue to the Homebrew/homebrew-core tap, or even better, submit a PR to fix it:
      /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/o/openldap.rb:89