streamripper: Fix `Homebrew/NoFileutilsRmrf` RuboCop offenses
- Also fix Sorbet error when `ENV.cppflags` is nil:

```
Error: An exception occurred within a child process:
    TypeError: Parameter 'newflags': Expected type String, got type NilClass
    Caller: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/s/streamripper.rb:31
    Definition: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/ENV/shared.rb:70 (SharedEnvExtension#append_to_cflags)
```
5a9b84d3059